language: ruby
script: 'true'
deploy:
  provider:
    provider: cloudfoundry
  api: https://api.de.a9s.eu
  username: anthonyroux
  password:
    secure: iDC1YkH77UVQCxuopRo/Q1Ql2eilwgRnHTzErG72N7rksMzLigLX8Y/BcRjElxscRotFAZzESO/ruVlHcTfKiIRzM6Y+EqAOTH5INk/HvdJwZDDz14SniG8+AyfLLEuTfjKecdNYu8hP+IfB9yquKAMgdrGh+blN7xunHbyOAcA=
  organization: anthonyroux
  space: test
  on:
    repo: anthonyroux/makeYourCount
