language: ruby
rvm:
  - 2.0.0
before_script:
  - "psql -c 'create database travis_ci_test;' -U postgres"
  - "rake db:migrate"
deploy:
  provider: heroku
  api_key:
    secure: cPK/R3a1FJGYuwERmK9f2LyJJ9aIJggKGPuyPTRMGco5fG85FVXzhtvrvjcjJmcDbeqxV4l4HpnMXg923xF0zANmjFsReWCCF4eJbJ/X+lbNIJ31Q+xmqaonuf4ADtbVDyaG86RRZsYvMGtqZrH120MiYCnomBkPgfsNiRotcm0=
  app: makeyourcount
  run: "rake db:migrate"

